### PR TITLE
Avoid adding : to GOPATH if it was unset

### PR DESCRIPTION
**Pull request by 0xmohit**
This avoids adding a `:` to `GOPATH` if it was unset to begin with.  As mentioned in https://github.com/pote/gvp/issues/39, a recent change (go 1.5) causes `source gvp` to fail if `GOPATH` was unset.

### CODE REVIEW

**Comment by 0xmohit** [comment]
I just realized that the corresponding change would also be needed in <https://github.com/pote/gvp/blob/master/test/init_in_and_out_test.sh>, i.e. change:

```
assert "echo $GOPATH" "$PWD/.godeps:$PWD:$original_GOPATH"
```
to

```
assert "echo $GOPATH" "$PWD/.godeps:$PWD${original_GOPATH:+:}$original_GOPATH"
```

**Comment by siddharthist** [comment]
@0xmohit Looks great! Would you mind also adding that change in the tests? I'll be happy to see this merged once that's ready.

**Comment by 0xmohit** [comment]
@siddharthist I've fixed the test.

**Comment by siddharthist** [comment]
Looks great. I'll test and merge this shortly. Thanks for your work!

**Comment by siddharthist** [comment]
@0xmohit Looks like there's something wrong with the test suite, there's a failing test but the build still results in a pass. Check this out: https://travis-ci.org/pote/gvp/builds/74823448

**Comment by siddharthist** [comment]
Looks like there is something messed up with the test suite, but it isn't related to this PR. I'll open a ticket to examine that myself. @0xmohit thanks again for your work!

**Pull request merged**
