### PR TITLE
fix syntax error in switch operator

### PR DESCRIPTION
**Pull request by Neyaz**
When I typed "gvp [command]" I got this error

/usr/local/bin/gvp: line 104: syntax error near unexpected token `;'
/usr/local/bin/gvp: line 104:`    "") ;& # This was sourced, no command was provided'

### CODE REVIEW

**Comment by siddharthist** [comment]
@Neyaz This is actually not a syntax error! You might have an old version of Bash. This syntax was introduced in version 4.0. Can you post the output of `bash --version`?

**Comment by Neyaz** [comment]
@siddharthist  
3.2.57(1)-release (x86_64-apple-darwin14)

Yes, I have old version.
But i think that's better because it's only one error when working with the old version. Doesn't need to update something or fix code.

**Comment by siddharthist** [comment]
@Neyaz I see what you're saying. In that case, please revise your code so that the case fallthrough is accurately represented, and I'll happily merge.

**Comment by Neyaz** [comment]
@siddharthist  What do you mean?

**Comment by siddharthist** [comment]
@Neyaz I mean that the syntax ;& represents a case fall through, where the next case's code is also executed. It is distinct from the ;; syntax. If you're still not sure how to do this, I'm happy to help.

**Comment by Neyaz** [comment]
@siddharthist 

Done.

**Comment by siddharthist** [comment]
@Neyaz Thank you! I'll test this soon.

**Pull request merged**
