### PR TITLE
Refactored into a function, added prompt change

### LINKED ISSUE #19: Prefix shell prompt with gvp marker
Hello.

gvp is some sort of analogue of virtualenv from python world. When virtualenv is activated it adds prefix to shell prompt, so you always know that you are in, e.g.

```bash
vgarvardt:project vgarvardt$ source .env/bin/activate
(.env)vgarvardt:project vgarvardt$ deactivate
vgarvardt:project vgarvardt$
```

It would be very good if gvp had the same behaviour:

```bash
vgarvardt:project vgarvardt$ source gvp in
(.godeps)vgarvardt:project vgarvardt$ source gvp out
vgarvardt:project vgarvardt$
```

virtualenv allows to create virtualenv in any dir, and set prefix to env dir name, gvp uses same name, so same prefix would be nice in any case.

### LINKED ISSUE #20: gvp as a bash function
The `gvp in` and `gvp out` commands have to be sourced, which makes sense but is kinda cumbersome. Could gvp be factored into a bash function instead to remove the need for `source`?

I think this is how some environment managers, like chruby, are designed. The manager is a single [script](https://github.com/postmodern/chruby/blob/master/share/chruby/chruby.sh) that gets sourced in your bashrc. Then that script adds a function to your environment that does all the actual env modification.

My bash-fu is not good enough to contribute this myself, sorry!

### LINKED ISSUE #26: crash with 'source gvp' in zsh
I use zsh， with oh-my-zsh config。It's ok to run as `gvp`、`source gvp in`、`source gvp out`。but crash with `source gvp`

I need some help，can you help me?

### PR DESCRIPTION
**Pull request by siddharthist**
Also fixed zsh crash
Fixes #20, fixes #19, fixes #26.
Perhaps this puts me in good consideration for #30.

### CODE REVIEW

**Comment by pote** [comment]
That is some very tidy code! :+1:  

I would probably check the test suite status before merging (it's currently failing for this PR, the test suite is slightly frail though, so the problem might be there rather than in the main code, not sure)

**Comment by siddharthist** [comment]
Is this correct?
```
test ➤ source gvp
>> Local GOPATH set.
test ➤ ./run_all_tests.sh 
>> Now running all tests
>> Current test: init_in_and_out_test.sh
>> Local GOPATH set.
>> All 6 examples tests passed in 0.014s.
>> All Done
>> Build status: passing
```

**Comment by siddharthist** [comment]
@pote Do you need something else on this?

**Comment by pote** [comment]
@siddharthist fine by me, great work and thanks for helping out!  :ship: :shipit: :tada:

**Pull request merged**
